import { spawnSync } from "node:child_process";
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  uiThemeTokenValues,
  uiTokenCategories,
  uiTokenMetadata,
  type UiThemeTokens,
} from "../src/token-metadata.js";

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const checkOnly = process.argv.includes("--check");
const generatedHeader =
  "/* Generated by scripts/generate-theme-css.ts. Do not edit token blocks by hand. */";
const builtInThemeNames = ["bobba", "zleek", "atlas", "studio", "paper", "pop", "pulse"] as const;
const scopedThemeNames = [
  "bobba",
  "custom",
  "zleek",
  "atlas",
  "studio",
  "paper",
  "pop",
  "pulse",
] as const;
const cssFiles = {
  base: "base.css",
  styles: "styles.css",
  componentSources: "component-sources.css",
  themeScopes: "theme-scopes.css",
  docs: "docs/tokens.md",
  bobba: "bobba/styles.css",
  zleek: "zleek/styles.css",
  atlas: "atlas/styles.css",
  studio: "studio/styles.css",
  paper: "paper/styles.css",
  pop: "pop/styles.css",
  pulse: "pulse/styles.css",
} as const;

const generatedFiles = new Map<string, string>([
  [cssFiles.base, generateBaseStyles()],
  [cssFiles.styles, generateDefaultStyles()],
  [cssFiles.componentSources, generateComponentSources()],
  [cssFiles.themeScopes, generateThemeScopes()],
  [cssFiles.docs, generateTokenDocs()],
  [cssFiles.bobba, generateThemeStyles("bobba")],
]);

for (const themeName of ["zleek", "atlas", "studio", "paper", "pop", "pulse"] as const) {
  generatedFiles.set(cssFiles[themeName], generateThemeStyles(themeName));
}

const staleFiles: string[] = [];

for (const [relativeFile, content] of generatedFiles) {
  const filePath = path.join(packageRoot, relativeFile);
  const formattedContent = formatGeneratedContent(relativeFile, content);

  if (checkOnly) {
    const current = existsSync(filePath) ? readFileSync(filePath, "utf8") : "";

    if (current !== formattedContent) {
      staleFiles.push(relativeFile);
    }

    continue;
  }

  writeFileSync(filePath, formattedContent);
}

if (staleFiles.length > 0) {
  console.error("@moritzbrantner/ui generated token artifacts are stale:");

  for (const file of staleFiles) {
    console.error(`- ${file}`);
  }

  console.error("Run `bun run generate:tokens`.");
  process.exit(1);
}

if (!checkOnly) {
  console.log(`Generated ${generatedFiles.size} token artifacts`);
}

function generateBaseStyles(): string {
  return [
    generatedHeader,
    '@import "tailwindcss";',
    '@import "tw-animate-css";',
    "",
    "@custom-variant dark (&:is(.dark *));",
    "",
    generateTailwindThemeBlock(),
    "",
    generateShadcnCompat(),
    "",
    extractBaseStaticCss(),
  ].join("\n");
}

function generateComponentSources(): string {
  return [
    generatedHeader,
    '@import "tailwindcss/utilities.css" layer(utilities) source(none);',
    '@reference "./base.css";',
    "",
    '@source "./dist/**/*.{js,mjs}";',
    '@source "./src/**/*.{ts,tsx}";',
  ].join("\n");
}

function generateDefaultStyles(): string {
  return [
    generatedHeader,
    '@import "./base.css";',
    "",
    generateTokenBlock(":root", uiThemeTokenValues.bobba.light),
    "",
    generateTokenBlock(".dark", uiThemeTokenValues.bobba.dark),
  ].join("\n");
}

function generateThemeStyles(themeName: (typeof builtInThemeNames)[number]): string {
  return [
    generatedHeader,
    '@import "../base.css";',
    "",
    generateTokenBlock(":root", uiThemeTokenValues[themeName].light),
    "",
    generateTokenBlock(".dark", uiThemeTokenValues[themeName].dark),
  ].join("\n");
}

function generateThemeScopes(): string {
  const lightBlocks = scopedThemeNames.map((themeName) => {
    const selector =
      themeName === "bobba"
        ? '[data-ui-theme="bobba"]'
        : themeName === "custom"
          ? '[data-ui-theme="custom"]'
          : `[data-ui-theme="${themeName}"]`;

    return generateTokenBlock(selector, uiThemeTokenValues[themeName].light);
  });
  const darkBlocks = scopedThemeNames.map((themeName) => {
    const selector =
      `.dark [data-ui-theme="${themeName}"],\n` + `[data-ui-theme="${themeName}"].dark`;

    return generateTokenBlock(selector, uiThemeTokenValues[themeName].dark);
  });

  return [
    generatedHeader,
    '@import "./base.css";',
    "",
    ...lightBlocks.flatMap((block) => [block, ""]),
    ...darkBlocks.flatMap((block) => [block, ""]),
  ].join("\n");
}

function generateTokenDocs(): string {
  const lines = [
    "# Design Tokens",
    "",
    "Generated from `src/token-metadata.ts` by `bun run generate:tokens`.",
    "",
    "## Themes",
    "",
    "| Theme | Light tokens | Dark tokens |",
    "| --- | ---: | ---: |",
  ];

  for (const themeName of scopedThemeNames) {
    lines.push(
      `| ${themeName} | ${Object.keys(uiThemeTokenValues[themeName].light).length} | ${Object.keys(uiThemeTokenValues[themeName].dark).length} |`,
    );
  }

  lines.push("", "## Tokens", "", "| Token | Category | Description |", "| --- | --- | --- |");

  for (const category of uiTokenCategories) {
    for (const token of uiTokenMetadata.filter((item) => item.category === category)) {
      lines.push(`| \`${token.name}\` | ${token.category} | ${token.description} |`);
    }
  }

  return `${lines.join("\n")}\n`;
}

function generateTailwindThemeBlock(): string {
  const aliases = [
    ["--color-background", "var(--background)"],
    ["--color-foreground", "var(--foreground)"],
    ["--font-heading", "var(--font-heading-app)"],
    ["--font-sans", "var(--font-sans-app)"],
    ["--font-mono", "var(--font-mono-app)"],
    ...uiTokenMetadata
      .filter(
        (token) =>
          token.category === "color" &&
          token.name !== "--background" &&
          token.name !== "--foreground",
      )
      .map((token) => [`--color-${token.name.slice(2)}`, `var(${token.name})`] as const),
    ["--radius-sm", "calc(var(--radius) - 4px)"],
    ["--radius-md", "calc(var(--radius) - 2px)"],
    ["--radius-lg", "var(--radius)"],
    ["--radius-xl", "calc(var(--radius) + 4px)"],
    ["--radius-2xl", "calc(var(--radius) + 8px)"],
    ["--radius-3xl", "calc(var(--radius) + 12px)"],
    ["--radius-4xl", "calc(var(--radius) + 16px)"],
  ];

  return [
    "@theme inline {",
    ...aliases.map(([name, value]) => `  ${name}: ${value};`),
    "",
    "  @keyframes accordion-down {",
    "    from {",
    "      height: 0;",
    "    }",
    "",
    "    to {",
    "      height: var(--radix-accordion-content-height, var(--accordion-panel-height, auto));",
    "    }",
    "  }",
    "",
    "  @keyframes accordion-up {",
    "    from {",
    "      height: var(--radix-accordion-content-height, var(--accordion-panel-height, auto));",
    "    }",
    "",
    "    to {",
    "      height: 0;",
    "    }",
    "  }",
    "}",
  ].join("\n");
}

function generateShadcnCompat(): string {
  return [
    "@custom-variant data-open {",
    '  &:where([data-state="open"]),',
    '  &:where([data-open]:not([data-open="false"])) {',
    "    @slot;",
    "  }",
    "}",
    "",
    "@custom-variant data-closed {",
    '  &:where([data-state="closed"]),',
    '  &:where([data-closed]:not([data-closed="false"])) {',
    "    @slot;",
    "  }",
    "}",
    "",
    "@custom-variant data-checked {",
    '  &:where([data-state="checked"]),',
    '  &:where([data-checked]:not([data-checked="false"])) {',
    "    @slot;",
    "  }",
    "}",
    "",
    "@custom-variant data-unchecked {",
    '  &:where([data-state="unchecked"]),',
    '  &:where([data-unchecked]:not([data-unchecked="false"])) {',
    "    @slot;",
    "  }",
    "}",
    "",
    "@custom-variant data-selected {",
    '  &:where([data-selected="true"]) {',
    "    @slot;",
    "  }",
    "}",
    "",
    "@custom-variant data-disabled {",
    '  &:where([data-disabled="true"]),',
    '  &:where([data-disabled]:not([data-disabled="false"])) {',
    "    @slot;",
    "  }",
    "}",
    "",
    "@custom-variant data-active {",
    '  &:where([data-state="active"]),',
    '  &:where([data-active]:not([data-active="false"])) {',
    "    @slot;",
    "  }",
    "}",
    "",
    "@custom-variant data-horizontal {",
    '  &:where([data-orientation="horizontal"]) {',
    "    @slot;",
    "  }",
    "}",
    "",
    "@custom-variant data-vertical {",
    '  &:where([data-orientation="vertical"]) {',
    "    @slot;",
    "  }",
    "}",
    "",
    "@utility no-scrollbar {",
    "  -ms-overflow-style: none;",
    "  scrollbar-width: none;",
    "",
    "  &::-webkit-scrollbar {",
    "    display: none;",
    "  }",
    "}",
  ].join("\n");
}

function generateTokenBlock(selector: string, tokens: UiThemeTokens): string {
  return [
    `${selector} {`,
    ...uiTokenMetadata.map((token) => {
      const value = tokens[token.name];

      if (!value) {
        throw new Error(`${selector} is missing ${token.name}`);
      }

      return `  ${token.name}: ${value};`;
    }),
    "}",
  ].join("\n");
}

function extractStaticCss(relativeFile: string): string {
  const source = readFileSync(path.join(packageRoot, relativeFile), "utf8");
  const layerIndex = source.indexOf("@layer ");

  if (layerIndex === -1) {
    return "";
  }

  return `${source.slice(layerIndex).trim()}\n`;
}

function extractBaseStaticCss(): string {
  if (existsSync(path.join(packageRoot, cssFiles.base))) {
    return extractStaticCss(cssFiles.base);
  }

  return extractStaticCss(cssFiles.styles);
}

function formatGeneratedContent(relativeFile: string, content: string): string {
  const formatter = spawnSync(
    path.join(packageRoot, "node_modules/.bin/oxfmt"),
    ["--stdin-filepath", relativeFile],
    {
      cwd: packageRoot,
      encoding: "utf8",
      input: content,
      stdio: ["pipe", "pipe", "pipe"],
    },
  );

  if (formatter.status !== 0) {
    throw new Error(formatter.stderr || formatter.stdout || `Failed to format ${relativeFile}`);
  }

  return formatter.stdout;
}
