import { existsSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

import {
  componentRegistry,
  type ComponentRegistryEntry,
  type ComponentTier,
} from "../src/component-registry.js";

const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const catalogPath = path.join(packageRoot, "docs", "components.md");
const checkOnly = process.argv.includes("--check");
const tiers = ["stable", "patterns", "data", "shell", "social", "media", "labs"] as const;
const tierLabels = {
  stable: "Stable",
  patterns: "Patterns",
  data: "Data",
  shell: "Shell",
  social: "Social",
  media: "Media",
  labs: "Labs",
} as const satisfies Record<ComponentTier, string>;

const catalog = generateCatalog(componentRegistry);

if (checkOnly) {
  const current = existsSync(catalogPath) ? readFileSync(catalogPath, "utf8") : "";

  if (current !== catalog) {
    console.error(
      "@moritzbrantner/ui component catalog is stale. Run `bun run generate:components`.",
    );
    process.exit(1);
  }

  console.log("@moritzbrantner/ui component catalog verified");
  process.exit(0);
}

writeFileSync(catalogPath, catalog);
console.log(`Generated ${path.relative(packageRoot, catalogPath)}`);

function generateCatalog(entries: readonly ComponentRegistryEntry[]) {
  const lines: string[] = [
    "# Component Catalog",
    "",
    "Generated from `src/component-registry.ts` by `bun run generate:components`.",
    "Do not edit this file by hand.",
    "",
    "## Summary",
    "",
    `- Total public components: ${entries.length}`,
    ...tiers.map((tier) => `- ${tierLabels[tier]} components: ${countTier(entries, tier)}`),
    `- Root-exported components: ${entries.filter((entry) => entry.rootExport).length}`,
    `- Deprecated components: ${entries.filter((entry) => entry.deprecatedSince).length}`,
    "",
  ];

  for (const tier of tiers) {
    lines.push(`## ${tierLabels[tier]}`, "");
    lines.push(...formatTierTable(entries.filter((item) => item.tier === tier)));

    lines.push("");
  }

  return `${lines.join("\n").trimEnd()}\n`;
}

function countTier(entries: readonly ComponentRegistryEntry[], tier: ComponentTier) {
  return entries.filter((entry) => entry.tier === tier).length;
}

function formatTierTable(entries: readonly ComponentRegistryEntry[]) {
  const headers = [
    "Component",
    "Status",
    "Root Export",
    "Public Import",
    "Stories",
    "Tests",
    "Notes",
  ];
  const rows = entries.map((entry) => [
    escapeTableCell(entry.name),
    escapeTableCell(entry.status),
    entry.rootExport ? "yes" : "no",
    `\`${entry.publicSubpath}\``,
    formatFileLinks(entry.storyFiles),
    formatFileLinks(entry.testFiles),
    escapeTableCell(formatNotes(entry)),
  ]);
  const widths = headers.map((header, columnIndex) =>
    Math.max(header.length, ...rows.map((row) => row[columnIndex].length)),
  );

  return [
    formatTableRow(headers, widths),
    formatTableRow(
      widths.map((width) => "-".repeat(width)),
      widths,
    ),
    ...rows.map((row) => formatTableRow(row, widths)),
  ];
}

function formatTableRow(cells: readonly string[], widths: readonly number[]) {
  return `| ${cells.map((cell, index) => cell.padEnd(widths[index])).join(" | ")} |`;
}

function formatFileLinks(files: readonly string[]) {
  if (files.length === 0) {
    return "none";
  }

  return files.map((file) => `[${escapeTableCell(file)}](../${encodeURI(file)})`).join(", ");
}

function formatNotes(entry: ComponentRegistryEntry) {
  const parts = [entry.reason];

  if (entry.deprecatedSince) {
    parts.push(
      `Deprecated since ${entry.deprecatedSince}.${entry.migration ? ` ${entry.migration}` : ""}`,
    );
  }

  return parts.join(" ");
}

function escapeTableCell(value: string) {
  return value.replace(/\|/g, "\\|").replace(/\n/g, " ");
}
