type ComponentTier = "stable" | "patterns" | "labs" | "legacy";

type ComponentStatus = "stable" | "pattern" | "lab" | "legacy";

type ComponentRegistryEntry = {
  name: string;
  fileName: string;
  tier: ComponentTier;
  rootExport: boolean;
  publicSubpath: string;
  storyFiles: readonly string[];
  testFiles: readonly string[];
  status: ComponentStatus;
  reason: string;
  deprecatedSince?: string;
  migration?: string;
};

const componentRegistry = [
  {
    name: "accordion",
    fileName: "accordion",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/accordion",
    storyFiles: ["src/components/stable/accordion.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "alert",
    fileName: "alert",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/alert",
    storyFiles: ["src/components/stable/alert.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "alert-dialog",
    fileName: "alert-dialog",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/alert-dialog",
    storyFiles: ["src/components/stable/primitive-overlays.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "angle-input",
    fileName: "angle-input",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/angle-input",
    storyFiles: ["src/components/stable/angle-input.stories.tsx"],
    testFiles: ["src/components/stable/angle-input.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "aspect-ratio",
    fileName: "aspect-ratio",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/aspect-ratio",
    storyFiles: ["src/components/stable/primitive-layout.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "avatar",
    fileName: "avatar",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/avatar",
    storyFiles: ["src/components/stable/avatar.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "avatar-collection",
    fileName: "avatar-collection",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/avatar-collection",
    storyFiles: ["src/components/stable/avatar-collection.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "badge",
    fileName: "badge",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/badge",
    storyFiles: ["src/components/stable/badge.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "breadcrumb",
    fileName: "breadcrumb",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/breadcrumb",
    storyFiles: ["src/components/stable/breadcrumb.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "button",
    fileName: "button",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/button",
    storyFiles: ["src/components/stable/button.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "button-group",
    fileName: "button-group",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/button-group",
    storyFiles: ["src/components/stable/primitive-actions.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "calendar",
    fileName: "calendar",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/calendar",
    storyFiles: ["src/components/stable/calendar.stories.tsx"],
    testFiles: ["src/components/stable/calendar.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "card",
    fileName: "card",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/card",
    storyFiles: ["src/components/stable/card.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "carousel",
    fileName: "carousel",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/carousel",
    storyFiles: ["src/components/stable/primitive-layout.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "chart",
    fileName: "chart",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/chart",
    storyFiles: ["src/components/stable/chart.stories.tsx"],
    testFiles: ["src/components/stable/chart.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "comparison-matrix",
    fileName: "comparison-matrix",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/comparison-matrix",
    storyFiles: ["src/components/stable/comparison-matrix.stories.tsx"],
    testFiles: ["src/components/stable/comparison-matrix.test.tsx"],
    status: "stable",
    reason: "Business visualization component for dashboard and report comparisons.",
  },
  {
    name: "checkbox",
    fileName: "checkbox",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/checkbox",
    storyFiles: ["src/components/stable/primitive-actions.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "citation",
    fileName: "citation",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/citation",
    storyFiles: ["src/components/stable/citation.stories.tsx"],
    testFiles: ["src/components/stable/citation.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "code-block",
    fileName: "code-block",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/code-block",
    storyFiles: ["src/components/stable/primitive-layout.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "collapsible",
    fileName: "collapsible",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/collapsible",
    storyFiles: ["src/components/stable/primitive-layout.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "combobox",
    fileName: "combobox",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/combobox",
    storyFiles: ["src/components/stable/combobox.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "command",
    fileName: "command",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/command",
    storyFiles: ["src/components/stable/primitive-overlays.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "context-menu",
    fileName: "context-menu",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/context-menu",
    storyFiles: ["src/components/stable/primitive-overlays.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "copy-button",
    fileName: "copy-button",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/copy-button",
    storyFiles: ["src/components/stable/copy-button.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "date-picker",
    fileName: "date-picker",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/date-picker",
    storyFiles: ["src/components/stable/date-picker.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "description-list",
    fileName: "description-list",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/description-list",
    storyFiles: ["src/components/stable/primitive-layout.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "dialog",
    fileName: "dialog",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/dialog",
    storyFiles: ["src/components/stable/dialog.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "direction",
    fileName: "direction",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/direction",
    storyFiles: ["src/components/stable/primitive-layout.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "drawer",
    fileName: "drawer",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/drawer",
    storyFiles: ["src/components/stable/primitive-overlays.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "dropdown-menu",
    fileName: "dropdown-menu",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/dropdown-menu",
    storyFiles: ["src/components/stable/dropdown-menu.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "empty",
    fileName: "empty",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/empty",
    storyFiles: ["src/components/stable/primitive-layout.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "field",
    fileName: "field",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/field",
    storyFiles: ["src/components/stable/primitive-forms.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "funnel-chart",
    fileName: "funnel-chart",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/funnel-chart",
    storyFiles: ["src/components/stable/funnel-chart.stories.tsx"],
    testFiles: ["src/components/stable/funnel-chart.test.tsx"],
    status: "stable",
    reason: "Business visualization component for conversion, pipeline, and dropoff summaries.",
  },
  {
    name: "form-layout",
    fileName: "form-layout",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/form-layout",
    storyFiles: ["src/components/stable/form-layout.stories.tsx"],
    testFiles: ["src/components/stable/form-layout.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "hover-card",
    fileName: "hover-card",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/hover-card",
    storyFiles: ["src/components/stable/primitive-overlays.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "infographic",
    fileName: "infographic",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/infographic",
    storyFiles: ["src/components/stable/infographic.stories.tsx"],
    testFiles: ["src/components/stable/infographic.test.tsx"],
    status: "stable",
    reason: "Business visualization layout toolkit for release reports and stakeholder summaries.",
  },
  {
    name: "input",
    fileName: "input",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/input",
    storyFiles: ["src/components/stable/primitive-components.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "input-group",
    fileName: "input-group",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/input-group",
    storyFiles: ["src/components/stable/primitive-forms.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "input-otp",
    fileName: "input-otp",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/input-otp",
    storyFiles: ["src/components/stable/primitive-forms.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "item",
    fileName: "item",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/item",
    storyFiles: ["src/components/stable/primitive-layout.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "kbd",
    fileName: "kbd",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/kbd",
    storyFiles: ["src/components/stable/primitive-actions.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "keyboard",
    fileName: "keyboard",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/keyboard",
    storyFiles: ["src/components/stable/keyboard.stories.tsx"],
    testFiles: ["src/components/stable/keyboard.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "label",
    fileName: "label",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/label",
    storyFiles: ["src/components/stable/primitive-forms.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "language-switcher",
    fileName: "language-switcher",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/language-switcher",
    storyFiles: ["src/components/stable/language-switcher.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "loading-bar",
    fileName: "loading-bar",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/loading-bar",
    storyFiles: ["src/components/stable/primitive-actions.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "menubar",
    fileName: "menubar",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/menubar",
    storyFiles: ["src/components/stable/primitive-overlays.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "metric-strip",
    fileName: "metric-strip",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/metric-strip",
    storyFiles: ["src/components/stable/metric-strip.stories.tsx"],
    testFiles: ["src/components/stable/metric-strip.test.tsx"],
    status: "stable",
    reason: "Business visualization component for dense KPI summaries.",
  },
  {
    name: "mobile-slide",
    fileName: "mobile-slide",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/mobile-slide",
    storyFiles: ["src/components/stable/primitive-overlays.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "native-select",
    fileName: "native-select",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/native-select",
    storyFiles: ["src/components/stable/primitive-forms.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "navigation-menu",
    fileName: "navigation-menu",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/navigation-menu",
    storyFiles: ["src/components/stable/primitive-overlays.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "org-chart",
    fileName: "org-chart",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/org-chart",
    storyFiles: ["src/components/stable/org-chart.stories.tsx"],
    testFiles: ["src/components/stable/org-chart.test.tsx"],
    status: "stable",
    reason: "Business visualization component for compact read-only hierarchy charts.",
  },
  {
    name: "pagination",
    fileName: "pagination",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/pagination",
    storyFiles: ["src/components/stable/pagination.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "popover",
    fileName: "popover",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/popover",
    storyFiles: ["src/components/stable/primitive-overlays.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "process-map",
    fileName: "process-map",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/process-map",
    storyFiles: ["src/components/stable/process-map.stories.tsx"],
    testFiles: ["src/components/stable/process-map.test.tsx"],
    status: "stable",
    reason: "Business visualization component for read-only process and lifecycle diagrams.",
  },
  {
    name: "progress",
    fileName: "progress",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/progress",
    storyFiles: ["src/components/stable/primitive-actions.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "radio-group",
    fileName: "radio-group",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/radio-group",
    storyFiles: ["src/components/stable/primitive-actions.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "relationship-map",
    fileName: "relationship-map",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/relationship-map",
    storyFiles: ["src/components/stable/relationship-map.stories.tsx"],
    testFiles: ["src/components/stable/relationship-map.test.tsx"],
    status: "stable",
    reason: "Business visualization component for read-only dependency and stakeholder maps.",
  },
  {
    name: "resizable",
    fileName: "resizable",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/resizable",
    storyFiles: ["src/components/stable/resizable.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "resizable-tabs",
    fileName: "resizable-tabs",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/resizable-tabs",
    storyFiles: ["src/components/stable/resizable-tabs.stories.tsx"],
    testFiles: ["src/components/stable/resizable-tabs.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "scroll-area",
    fileName: "scroll-area",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/scroll-area",
    storyFiles: ["src/components/stable/primitive-forms.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "select",
    fileName: "select",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/select",
    storyFiles: ["src/components/stable/primitive-forms.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "separator",
    fileName: "separator",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/separator",
    storyFiles: ["src/components/stable/primitive-components.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "sheet",
    fileName: "sheet",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/sheet",
    storyFiles: ["src/components/stable/sheet.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "sidebar",
    fileName: "sidebar",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/sidebar",
    storyFiles: ["src/components/stable/primitive-overlays.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "skeleton",
    fileName: "skeleton",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/skeleton",
    storyFiles: ["src/components/stable/primitive-components.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "slider",
    fileName: "slider",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/slider",
    storyFiles: ["src/components/stable/primitive-actions.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "sonner",
    fileName: "sonner",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/sonner",
    storyFiles: ["src/components/stable/sonner.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "spinner",
    fileName: "spinner",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/spinner",
    storyFiles: ["src/components/stable/spinner.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "stat",
    fileName: "stat",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/stat",
    storyFiles: ["src/components/stable/primitive-layout.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "switch",
    fileName: "switch",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/switch",
    storyFiles: ["src/components/stable/primitive-actions.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "table",
    fileName: "table",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/table",
    storyFiles: ["src/components/stable/primitive-components.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "tabs",
    fileName: "tabs",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/tabs",
    storyFiles: ["src/components/stable/tabs.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "tag-input",
    fileName: "tag-input",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/tag-input",
    storyFiles: ["src/components/stable/tag-input.stories.tsx"],
    testFiles: ["src/components/stable/tag-input.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "textarea",
    fileName: "textarea",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/textarea",
    storyFiles: ["src/components/stable/primitive-forms.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "theme-mode-switch",
    fileName: "theme-mode-switch",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/theme-mode-switch",
    storyFiles: ["src/components/stable/theme-mode-switch.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "toast",
    fileName: "toast",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/toast",
    storyFiles: ["src/components/stable/primitive-overlays.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "toggle",
    fileName: "toggle",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/toggle",
    storyFiles: ["src/components/stable/primitive-actions.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "toggle-group",
    fileName: "toggle-group",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/toggle-group",
    storyFiles: ["src/components/stable/primitive-actions.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "toggle-setting",
    fileName: "toggle-setting",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/toggle-setting",
    storyFiles: ["src/components/stable/primitive-actions.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "toolbar",
    fileName: "toolbar",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/toolbar",
    storyFiles: ["src/components/stable/toolbar.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "tooltip",
    fileName: "tooltip",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/tooltip",
    storyFiles: ["src/components/stable/tooltip.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "typography",
    fileName: "typography",
    tier: "stable",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/stable/typography",
    storyFiles: ["src/components/stable/typography.stories.tsx"],
    testFiles: ["src/components/stable/stable-contract.test.tsx"],
    status: "stable",
    reason: "Reusable primitive or low-level control with stable support.",
  },
  {
    name: "account-menu",
    fileName: "account-menu",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/account-menu",
    storyFiles: ["src/components/patterns/account-menu.stories.tsx"],
    testFiles: ["src/components/patterns/patterns-contract.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "action-menu",
    fileName: "action-menu",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/action-menu",
    storyFiles: ["src/components/patterns/action-menu.stories.tsx"],
    testFiles: ["src/components/patterns/action-menu.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "action-sheet",
    fileName: "action-sheet",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/action-sheet",
    storyFiles: ["src/components/patterns/action-sheet.stories.tsx"],
    testFiles: ["src/components/patterns/action-sheet.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "app-layout",
    fileName: "app-layout",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/app-layout",
    storyFiles: ["src/components/patterns/app-layout.stories.tsx"],
    testFiles: ["src/components/patterns/app-layout.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "chat",
    fileName: "chat",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/chat",
    storyFiles: ["src/components/patterns/release-readiness.stories.tsx"],
    testFiles: ["src/components/patterns/patterns-contract.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "chat-box",
    fileName: "chat-box",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/chat-box",
    storyFiles: ["src/components/patterns/release-readiness.stories.tsx"],
    testFiles: ["src/components/patterns/patterns-contract.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "command-palette",
    fileName: "command-palette",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/command-palette",
    storyFiles: ["src/components/patterns/command-palette.stories.tsx"],
    testFiles: ["src/components/patterns/command-palette.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "connection-status",
    fileName: "connection-status",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/connection-status",
    storyFiles: ["src/components/patterns/connection-status.stories.tsx"],
    testFiles: ["src/components/patterns/connection-status.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "confirm-action",
    fileName: "confirm-action",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/confirm-action",
    storyFiles: ["src/components/patterns/confirm-action.stories.tsx"],
    testFiles: ["src/components/patterns/patterns-contract.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "context-action-menu",
    fileName: "context-action-menu",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/context-action-menu",
    storyFiles: ["src/components/patterns/context-action-menu.stories.tsx"],
    testFiles: ["src/components/patterns/context-action-menu.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "data-grid",
    fileName: "data-grid",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/data-grid",
    storyFiles: ["src/components/patterns/data-grid.stories.tsx"],
    testFiles: ["src/components/patterns/data-grid.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "details-panel",
    fileName: "details-panel",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/details-panel",
    storyFiles: ["src/components/patterns/details-panel.stories.tsx"],
    testFiles: ["src/components/patterns/patterns-contract.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "disclosure-panel",
    fileName: "disclosure-panel",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/disclosure-panel",
    storyFiles: ["src/components/patterns/disclosure-panel.stories.tsx"],
    testFiles: ["src/components/patterns/disclosure-panel.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "dropzone",
    fileName: "dropzone",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/dropzone",
    storyFiles: ["src/components/patterns/dropzone.stories.tsx"],
    testFiles: ["src/components/patterns/patterns-contract.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "filter-bar",
    fileName: "filter-bar",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/filter-bar",
    storyFiles: ["src/components/patterns/filter-bar.stories.tsx"],
    testFiles: ["src/components/patterns/filter-bar.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "hover-preview",
    fileName: "hover-preview",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/hover-preview",
    storyFiles: ["src/components/patterns/hover-preview.stories.tsx"],
    testFiles: ["src/components/patterns/hover-preview.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "menu-actions",
    fileName: "menu-actions",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/menu-actions",
    storyFiles: ["src/components/patterns/release-readiness.stories.tsx"],
    testFiles: ["src/components/patterns/patterns-contract.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "notification-menu",
    fileName: "notification-menu",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/notification-menu",
    storyFiles: ["src/components/patterns/notification-menu.stories.tsx"],
    testFiles: ["src/components/patterns/patterns-contract.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "platform-navbar",
    fileName: "platform-navbar",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/platform-navbar",
    storyFiles: ["src/components/patterns/platform-navbar.stories.tsx"],
    testFiles: ["src/components/patterns/patterns-contract.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "platform-navbar-actions",
    fileName: "platform-navbar-actions",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/platform-navbar-actions",
    storyFiles: ["src/components/patterns/platform-navbar.stories.tsx"],
    testFiles: ["src/components/stable/overlays-and-navigation.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "responsive-action-menu",
    fileName: "responsive-action-menu",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/responsive-action-menu",
    storyFiles: ["src/components/patterns/responsive-action-menu.stories.tsx"],
    testFiles: ["src/components/patterns/responsive-action-menu.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "resource-list",
    fileName: "resource-list",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/resource-list",
    storyFiles: ["src/components/patterns/resource-list.stories.tsx"],
    testFiles: ["src/components/patterns/patterns-contract.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "search-field",
    fileName: "search-field",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/search-field",
    storyFiles: ["src/components/patterns/search-field.stories.tsx"],
    testFiles: ["src/components/patterns/search-field.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "selection-toolbar",
    fileName: "selection-toolbar",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/selection-toolbar",
    storyFiles: ["src/components/patterns/selection-toolbar.stories.tsx"],
    testFiles: ["src/components/patterns/selection-toolbar.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "shortcut-help",
    fileName: "shortcut-help",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/shortcut-help",
    storyFiles: ["src/components/patterns/shortcut-help.stories.tsx"],
    testFiles: ["src/components/patterns/shortcut-help.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "social-actions",
    fileName: "social-actions",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/social-actions",
    storyFiles: ["src/components/patterns/release-readiness.stories.tsx"],
    testFiles: ["src/components/patterns/patterns-contract.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "social-feed",
    fileName: "social-feed",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/social-feed",
    storyFiles: ["src/components/patterns/release-readiness.stories.tsx"],
    testFiles: ["src/components/patterns/patterns-contract.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "state-view",
    fileName: "state-view",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/state-view",
    storyFiles: ["src/components/patterns/state-view.stories.tsx"],
    testFiles: ["src/components/patterns/state-view.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "stepper",
    fileName: "stepper",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/stepper",
    storyFiles: ["src/components/patterns/stepper.stories.tsx"],
    testFiles: ["src/components/patterns/patterns-contract.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "upload-queue",
    fileName: "upload-queue",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/upload-queue",
    storyFiles: ["src/components/patterns/upload-queue.stories.tsx"],
    testFiles: ["src/components/patterns/upload-queue.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "view-header",
    fileName: "view-header",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/view-header",
    storyFiles: ["src/components/patterns/view-header.stories.tsx"],
    testFiles: ["src/components/patterns/patterns-contract.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "workbench-layout",
    fileName: "workbench-layout",
    tier: "patterns",
    rootExport: true,
    publicSubpath: "@moritzbrantner/ui/components/patterns/workbench-layout",
    storyFiles: ["src/components/patterns/workbench-layout.stories.tsx"],
    testFiles: ["src/components/patterns/workbench-layout.test.tsx"],
    status: "pattern",
    reason: "Reusable state-light application pattern exported from the root API.",
  },
  {
    name: "annotation-canvas",
    fileName: "annotation-canvas",
    tier: "labs",
    rootExport: false,
    publicSubpath: "@moritzbrantner/ui/components/labs/annotation-canvas",
    storyFiles: [],
    testFiles: [],
    status: "lab",
    reason: "Advanced or specialized surface available through explicit labs imports.",
  },
  {
    name: "asset-browser",
    fileName: "asset-browser",
    tier: "labs",
    rootExport: false,
    publicSubpath: "@moritzbrantner/ui/components/labs/asset-browser",
    storyFiles: [],
    testFiles: [],
    status: "lab",
    reason: "Advanced or specialized surface available through explicit labs imports.",
  },
  {
    name: "component-editor",
    fileName: "component-editor",
    tier: "labs",
    rootExport: false,
    publicSubpath: "@moritzbrantner/ui/components/labs/component-editor",
    storyFiles: [],
    testFiles: [],
    status: "lab",
    reason: "Advanced or specialized surface available through explicit labs imports.",
  },
  {
    name: "document-viewer",
    fileName: "document-viewer",
    tier: "labs",
    rootExport: false,
    publicSubpath: "@moritzbrantner/ui/components/labs/document-viewer",
    storyFiles: [],
    testFiles: [],
    status: "lab",
    reason: "Advanced or specialized surface available through explicit labs imports.",
  },
  {
    name: "gantt",
    fileName: "gantt",
    tier: "labs",
    rootExport: false,
    publicSubpath: "@moritzbrantner/ui/components/labs/gantt",
    storyFiles: [],
    testFiles: [],
    status: "lab",
    reason: "Advanced or specialized surface available through explicit labs imports.",
  },
  {
    name: "image-cropper",
    fileName: "image-cropper",
    tier: "labs",
    rootExport: false,
    publicSubpath: "@moritzbrantner/ui/components/labs/image-cropper",
    storyFiles: [],
    testFiles: [],
    status: "lab",
    reason: "Advanced or specialized surface available through explicit labs imports.",
  },
  {
    name: "image-filter-editor",
    fileName: "image-filter-editor",
    tier: "labs",
    rootExport: false,
    publicSubpath: "@moritzbrantner/ui/components/labs/image-filter-editor",
    storyFiles: [],
    testFiles: [],
    status: "lab",
    reason: "Advanced or specialized surface available through explicit labs imports.",
  },
  {
    name: "inspector-panel",
    fileName: "inspector-panel",
    tier: "labs",
    rootExport: false,
    publicSubpath: "@moritzbrantner/ui/components/labs/inspector-panel",
    storyFiles: [],
    testFiles: [],
    status: "lab",
    reason: "Advanced or specialized surface available through explicit labs imports.",
  },
  {
    name: "logical-argument",
    fileName: "logical-argument",
    tier: "labs",
    rootExport: false,
    publicSubpath: "@moritzbrantner/ui/components/labs/logical-argument",
    storyFiles: [],
    testFiles: [],
    status: "lab",
    reason: "Advanced or specialized surface available through explicit labs imports.",
  },
  {
    name: "profile-summary",
    fileName: "profile-summary",
    tier: "labs",
    rootExport: false,
    publicSubpath: "@moritzbrantner/ui/components/labs/profile-summary",
    storyFiles: [],
    testFiles: [],
    status: "lab",
    reason: "Advanced or specialized surface available through explicit labs imports.",
  },
  {
    name: "query-builder",
    fileName: "query-builder",
    tier: "labs",
    rootExport: false,
    publicSubpath: "@moritzbrantner/ui/components/labs/query-builder",
    storyFiles: [],
    testFiles: [],
    status: "lab",
    reason: "Advanced or specialized surface available through explicit labs imports.",
  },
  {
    name: "terminal",
    fileName: "terminal",
    tier: "labs",
    rootExport: false,
    publicSubpath: "@moritzbrantner/ui/components/labs/terminal",
    storyFiles: [],
    testFiles: [],
    status: "lab",
    reason: "Advanced or specialized surface available through explicit labs imports.",
  },
  {
    name: "timeline",
    fileName: "timeline",
    tier: "labs",
    rootExport: false,
    publicSubpath: "@moritzbrantner/ui/components/labs/timeline",
    storyFiles: [],
    testFiles: [],
    status: "lab",
    reason: "Advanced or specialized surface available through explicit labs imports.",
  },
  {
    name: "timeline-editor",
    fileName: "timeline-editor",
    tier: "labs",
    rootExport: false,
    publicSubpath: "@moritzbrantner/ui/components/labs/timeline-editor",
    storyFiles: [],
    testFiles: [],
    status: "lab",
    reason: "Advanced or specialized surface available through explicit labs imports.",
  },
  {
    name: "tree-view",
    fileName: "tree-view",
    tier: "labs",
    rootExport: false,
    publicSubpath: "@moritzbrantner/ui/components/labs/tree-view",
    storyFiles: [],
    testFiles: [],
    status: "lab",
    reason: "Advanced or specialized surface available through explicit labs imports.",
  },
  {
    name: "uml-diagram",
    fileName: "uml-diagram",
    tier: "labs",
    rootExport: false,
    publicSubpath: "@moritzbrantner/ui/components/labs/uml-diagram",
    storyFiles: [],
    testFiles: [],
    status: "lab",
    reason: "Advanced or specialized surface available through explicit labs imports.",
  },
  {
    name: "workflow-builder",
    fileName: "workflow-builder",
    tier: "labs",
    rootExport: false,
    publicSubpath: "@moritzbrantner/ui/components/labs/workflow-builder",
    storyFiles: [],
    testFiles: [],
    status: "lab",
    reason: "Advanced or specialized surface available through explicit labs imports.",
  },
  {
    name: "workflow-node",
    fileName: "workflow-node",
    tier: "labs",
    rootExport: false,
    publicSubpath: "@moritzbrantner/ui/components/labs/workflow-node",
    storyFiles: [],
    testFiles: [],
    status: "lab",
    reason: "Advanced or specialized surface available through explicit labs imports.",
  },
  {
    name: "data-table",
    fileName: "data-table",
    tier: "legacy",
    rootExport: false,
    publicSubpath: "@moritzbrantner/ui/components/legacy/data-table",
    storyFiles: ["src/components/legacy/data-table.stories.tsx"],
    testFiles: ["src/components/legacy/legacy-contract.test.tsx"],
    status: "legacy",
    reason: "Legacy compatibility surface retained outside the root API.",
    deprecatedSince: "0.8.0",
    migration: "Use DataGrid from @moritzbrantner/ui/components/patterns/data-grid.",
  },
] as const satisfies readonly ComponentRegistryEntry[];

export { componentRegistry };
export type { ComponentRegistryEntry, ComponentStatus, ComponentTier };
