const uiTokenCategories = [
  "color",
  "font",
  "radius",
  "surface",
  "control",
  "focus",
  "motion",
  "shadow",
  "component",
] as const;

type UiTokenCategory = (typeof uiTokenCategories)[number];

type UiTokenMetadata = {
  name: string;
  category: UiTokenCategory;
};

const uiTokenMetadata = [
  { name: "--font-sans-app", category: "font" },
  { name: "--font-mono-app", category: "font" },
  { name: "--radius", category: "radius" },
  { name: "--glass-shadow", category: "shadow" },
  { name: "--glass-interactive-shadow", category: "shadow" },
  { name: "--background", category: "color" },
  { name: "--foreground", category: "color" },
  { name: "--card", category: "color" },
  { name: "--card-foreground", category: "color" },
  { name: "--popover", category: "color" },
  { name: "--popover-foreground", category: "color" },
  { name: "--primary", category: "color" },
  { name: "--primary-foreground", category: "color" },
  { name: "--secondary", category: "color" },
  { name: "--secondary-foreground", category: "color" },
  { name: "--muted", category: "color" },
  { name: "--muted-foreground", category: "color" },
  { name: "--accent", category: "color" },
  { name: "--accent-foreground", category: "color" },
  { name: "--destructive", category: "color" },
  { name: "--border", category: "color" },
  { name: "--input", category: "color" },
  { name: "--ring", category: "color" },
  { name: "--chart-1", category: "color" },
  { name: "--chart-2", category: "color" },
  { name: "--chart-3", category: "color" },
  { name: "--chart-4", category: "color" },
  { name: "--chart-5", category: "color" },
  { name: "--sidebar", category: "color" },
  { name: "--sidebar-foreground", category: "color" },
  { name: "--sidebar-primary", category: "color" },
  { name: "--sidebar-primary-foreground", category: "color" },
  { name: "--sidebar-accent", category: "color" },
  { name: "--sidebar-accent-foreground", category: "color" },
  { name: "--sidebar-border", category: "color" },
  { name: "--sidebar-ring", category: "color" },
  { name: "--ui-radius-control", category: "radius" },
  { name: "--ui-radius-surface", category: "radius" },
  { name: "--ui-radius-overlay", category: "radius" },
  { name: "--ui-control-height-xs", category: "control" },
  { name: "--ui-control-height-sm", category: "control" },
  { name: "--ui-control-height-md", category: "control" },
  { name: "--ui-control-height-lg", category: "control" },
  { name: "--ui-control-padding-x-sm", category: "control" },
  { name: "--ui-control-padding-x-md", category: "control" },
  { name: "--ui-control-gap", category: "control" },
  { name: "--ui-surface-padding-sm", category: "surface" },
  { name: "--ui-surface-padding-md", category: "surface" },
  { name: "--ui-surface-gap", category: "surface" },
  { name: "--ui-focus-ring-width", category: "focus" },
  { name: "--ui-motion-hover-y", category: "motion" },
  { name: "--ui-motion-hover-scale", category: "motion" },
  { name: "--ui-shadow-surface", category: "shadow" },
  { name: "--ui-shadow-interactive", category: "shadow" },
  { name: "--ui-button-height-xs", category: "component" },
  { name: "--ui-button-height-sm", category: "component" },
  { name: "--ui-button-height-md", category: "component" },
  { name: "--ui-button-height-lg", category: "component" },
  { name: "--ui-button-padding-x-xs", category: "component" },
  { name: "--ui-button-padding-x-sm", category: "component" },
  { name: "--ui-button-padding-x-md", category: "component" },
  { name: "--ui-button-padding-x-lg", category: "component" },
  { name: "--ui-button-radius", category: "component" },
  { name: "--ui-input-height", category: "component" },
  { name: "--ui-input-padding-x", category: "component" },
  { name: "--ui-input-radius", category: "component" },
  { name: "--ui-card-padding", category: "component" },
  { name: "--ui-card-gap", category: "component" },
  { name: "--ui-card-radius", category: "component" },
  { name: "--ui-overlay-padding", category: "component" },
  { name: "--ui-overlay-gap", category: "component" },
  { name: "--ui-overlay-radius", category: "component" },
  { name: "--ui-menu-padding", category: "component" },
  { name: "--ui-menu-item-padding-x", category: "component" },
  { name: "--ui-menu-item-padding-y", category: "component" },
  { name: "--ui-menu-item-radius", category: "component" },
  { name: "--ui-toolbar-padding-x", category: "component" },
  { name: "--ui-toolbar-padding-y", category: "component" },
  { name: "--ui-toolbar-gap", category: "component" },
  { name: "--ui-toolbar-min-height", category: "component" },
  { name: "--ui-tabs-list-padding", category: "component" },
] as const satisfies readonly UiTokenMetadata[];

const uiTokenNames = uiTokenMetadata.map((token) => token.name) as UiTokenName[];

type UiTokenName = (typeof uiTokenMetadata)[number]["name"];
type UiThemeTokens = Partial<Record<UiTokenName, string>>;

export { uiTokenCategories, uiTokenMetadata, uiTokenNames };
export type { UiThemeTokens, UiTokenCategory, UiTokenMetadata, UiTokenName };
